### PR TITLE
Add support to click events

### PR DESCRIPTION
**Pull request by bailon**
Based on the solution provided by @Benvorth and the feedback from @stegben. 
I hope this time it will be accepted!

### CODE REVIEW

**Comment by bailon** [comment]
Updated tests and README.

**Comment by stegben** [comment]
Why closed?

**Comment by stegben** [comment]
LGTM, merged after your feedback

**Comment by tw0517tw** [comment]
Will it be better if we name that prop `onWordClick`? `clickEvent` sounds like a variable, not a function.

**Comment by bailon** [comment]
No idea why I closed, still learning the process here, sorry!

Should I update the prop name as proposed by @tw0517tw ?

**Comment by bailon** [comment]
Is there anything missing from my side that I can help with? Thanks!

**Comment by stegben** [comment]
Sorry for my late response, it looks good and I'll upload a new release. Thanks a lot!

**Pull request merged**
