### PR TITLE
add click event for text II

### PR DESCRIPTION
**Pull request by Benvorth**
fixed indent spaces
based on https://github.com/Yoctol/react-d3-cloud/pull/88

### CODE REVIEW

**Comment by stegben** [comment]
Hi, THX for the PR, but the CI is still not passing. Some coding style issue should be fixed.

To test ESLint on your local machine, run `npm run lint`.

**Comment by Benvorth** [comment]
Hi, I cant find the Problem, the commited file seems fine to me. Can you see the problem?

**Comment by stegben** [comment]
The fails came from linters. Run `npm run lint` on your local machine, it will tell you the coding style rules you break.

**Comment by wmhafiz** [comment]
Really need this feature for one of my project, hope this get merged soon! 💯

**Comment by stegben** [comment]
#96

**Pull request closed without merging**
